github: [ALi3naTEd0] # Replace with your GitHub Sponsors username if applicable
patreon: []          # Replace with your Patreon username if applicable
open_collective: []  # Replace with your Open Collective username if applicable
ko_fi: []            # Replace with your Ko-fi username if applicable
tidelift: []         # Replace with your Tidelift subscription URL if applicable
custom: []           # Add custom URLs for funding if applicable
