output: dist/
releases:
  - name: linux
    jobs:
      - name: release-linux
        package:
          platform: linux
          targets: [deb]  # Por ahora solo .deb para probar

  - name: macos
    jobs:
      - name: release-macos
        package:
          platform: macos
          target: dmg
