appimage:
  build: true
  exec: RateMe
  entrypoint: RateMe
  name: Rate Me
  version: 1.0.0
  arch: x86_64
  desktop_entry:
    name: Rate Me
    comment: Music Rating App
    categories: Utility
    icon: rateme
  resources:
    icon: assets/app-icon.png
    desktop: linux/rateme.desktop
  depends:
    - libgtk-3-0
    - libglu1-mesa
