name: Android Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        type: string
        default: '1.0.0-1'
  workflow_call:
    inputs:
      version:
        required: true
        type: string
        description: 'Version number'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Configure Gradle
        run: |
          mkdir -p $HOME/.gradle
          echo "org.gradle.java.home=$JAVA_HOME" >> $HOME/.gradle/gradle.properties
          echo "Current gradle.properties:"
          cat $HOME/.gradle/gradle.properties

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android/cache
          key: gradle-android-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/*.properties', 'pubspec.yaml') }}-${{ github.sha }}
          restore-keys: |
            gradle-android-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/*.properties', 'pubspec.yaml') }}-
            gradle-android-${{ runner.os }}-

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
          cache: true

      - name: Download Icons
        run: |
          mkdir -p assets
          curl -o assets/app-icon.png https://raw.githubusercontent.com/ALi3naTEd0/RateMe/rateme/assets/rateme.png
          curl -o assets/rateme.png https://raw.githubusercontent.com/ALi3naTEd0/RateMe/rateme/assets/rateme.png

      # More secure way to decode keystore - directly from base64 to file
      - name: Decode Keystore
        run: |
          echo "${{ secrets.UPLOAD_KEYSTORE }}" | base64 -d > android/app/upload-keystore.jks
          # Verify the keystore was created correctly
          ls -la android/app/upload-keystore.jks
          echo "Keystore file size: $(stat -c %s android/app/upload-keystore.jks) bytes"

      # Create key.properties with explicit path
      - name: Set up key.properties
        run: |
          touch android/key.properties
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=upload-keystore.jks" >> android/key.properties
          
          # Verify key.properties exists and has content
          echo "Key.properties location:"
          ls -la android/key.properties
          echo "Key.properties size: $(stat -c %s android/key.properties) bytes"
          echo "Key.properties contents (redacted):"
          grep -v "password" android/key.properties || true
          echo "keyAlias exists: $(grep -c "keyAlias" android/key.properties || echo "0")"
          echo "storeFile exists: $(grep -c "storeFile" android/key.properties || echo "0")"

      # First build universal APK
      - name: Build Universal APK
        run: |
          flutter pub get
          flutter build apk --release --verbose
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/RateMe_${{ inputs.version || github.event.inputs.version }}.apk
          
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rateme-universal
          path: build/app/outputs/flutter-apk/RateMe_${{ inputs.version || github.event.inputs.version }}.apk
          
      # Then build ABI-specific APKs
      - name: Build Split APKs
        run: |
          flutter build apk --release --split-per-abi --verbose
          mv build/app/outputs/flutter-apk/app-arm64-v8a-release.apk build/app/outputs/flutter-apk/RateMe_${{ inputs.version || github.event.inputs.version }}_arm64-v8a.apk
          mv build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk build/app/outputs/flutter-apk/RateMe_${{ inputs.version || github.event.inputs.version }}_armeabi-v7a.apk
          mv build/app/outputs/flutter-apk/app-x86_64-release.apk build/app/outputs/flutter-apk/RateMe_${{ inputs.version || github.event.inputs.version }}_x86_64.apk

      - name: Upload arm64-v8a APK
        uses: actions/upload-artifact@v4
        with:
          name: rateme-arm64-v8a
          path: build/app/outputs/flutter-apk/RateMe_${{ inputs.version || github.event.inputs.version }}_arm64-v8a.apk

      - name: Upload armeabi-v7a APK
        uses: actions/upload-artifact@v4
        with:
          name: rateme-armeabi-v7a
          path: build/app/outputs/flutter-apk/RateMe_${{ inputs.version || github.event.inputs.version }}_armeabi-v7a.apk

      - name: Upload x86_64 APK
        uses: actions/upload-artifact@v4
        with:
          name: rateme-x86_64
          path: build/app/outputs/flutter-apk/RateMe_${{ inputs.version || github.event.inputs.version }}_x86_64.apk
