name: Android Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Verify Java installation
        run: |
          echo "Java version:"
          java -version
          echo "JAVA_HOME:"
          echo $JAVA_HOME
          ls -la $JAVA_HOME

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
          cache: true

      - name: Configure Gradle
        run: |
          mkdir -p $HOME/.gradle
          echo "org.gradle.java.home=$JAVA_HOME" >> $HOME/.gradle/gradle.properties
          echo "Current gradle.properties:"
          cat $HOME/.gradle/gradle.properties

      # First build universal APK
      - name: Build Universal APK
        run: |
          flutter pub get
          flutter build apk --release --verbose
          
      - name: Upload Universal APK
        uses: actions/upload-artifact@v4
        with:
          name: RateMe-universal
          path: build/app/outputs/flutter-apk/app-release.apk
          
      # Then build ABI-specific APKs
      - name: Build Split APKs
        run: flutter build apk --release --split-per-abi

      - name: Upload arm64-v8a APK
        uses: actions/upload-artifact@v4
        with:
          name: RateMe-arm64-v8a
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk

      - name: Upload armeabi-v7a APK
        uses: actions/upload-artifact@v4
        with:
          name: RateMe-armeabi-v7a
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk

      - name: Upload x86_64 APK
        uses: actions/upload-artifact@v4
        with:
          name: RateMe-x86_64
          path: build/app/outputs/flutter-apk/app-x86_64-release.apk
