name: Flatpak Build

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

env:
  FLATPAK_ID: com.ali3nated0.rateme

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: rateme

      # Install all build dependencies first
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang \
            cmake \
            ninja-build \
            pkg-config \
            libgtk-3-dev \
            liblzma-dev \
            libstdc++-12-dev \
            # Flatpak dependencies
            flatpak \
            flatpak-builder \
            # Flutter dependencies
            xz-utils \
            libglu1-mesa

      # Then setup Flutter and build
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'

      - name: Build Flutter App
        run: |
          flutter config --enable-linux-desktop
          flutter doctor -v
          flutter build linux --release

      # Now continue with Flatpak steps
      - name: Setup Flatpak
        run: |
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          sudo flatpak install -y flathub org.freedesktop.Platform//23.08 org.freedesktop.Sdk//23.08

      - name: Create Flatpak Manifest
        run: |
          cat > com.ali3nated0.rateme.yml << EOF
          app-id: com.ali3nated0.rateme
          runtime: org.freedesktop.Platform
          runtime-version: '23.08'
          sdk: org.freedesktop.Sdk
          command: rateme
          # Set permissions and access
          finish-args:
            - --share=ipc
            - --socket=fallback-x11
            - --socket=wayland
            - --device=dri
            - --filesystem=home
          # Configure build and installation
          modules:
            - name: rateme
              buildsystem: simple
              build-commands:
                - cp -r . /app/
                - chmod +x /app/rateme
                - mkdir -p /app/share/applications /app/share/icons/hicolor/512x512/apps
                - cp assets/rateme.png /app/share/icons/hicolor/512x512/apps/
                - cp com.ali3nated0.rateme.desktop /app/share/applications/
              sources:
                - type: dir
                  path: build/linux/x64/release/bundle
          EOF

      - name: Build Flatpak Package
        run: |
          # Clean build directory or use --force-clean
          flatpak-builder --force-clean --repo=repo build com.ali3nated0.rateme.yml
          flatpak build-bundle repo RateMe_${{ inputs.version }}.flatpak $FLATPAK_ID

      - name: Upload Flatpak Package
        uses: actions/upload-artifact@v4
        with:
          name: RateMe-Flatpak
          path: RateMe_${{ inputs.version }}.flatpak
