name: Flatpak Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        type: string
        default: '1.0.0-1'
  workflow_call:
    inputs:
      version:
        required: true
        type: string
        description: 'Version number'

env:
  FLATPAK_ID: com.ali3nated0.rateme

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install all build dependencies first
      - name: Install Dependencies
        run: |
          sudo add-apt-repository -y ppa:flatpak/stable
          sudo apt-get update
          sudo apt-get install -y \
            flatpak \
            flatpak-builder \
            xz-utils \
            clang \
            cmake \
            ninja-build \
            pkg-config \
            libgtk-3-dev \
            liblzma-dev \
            libstdc++-12-dev \
            libglu1-mesa \
            imagemagick

      # Setup Flatpak first
      - name: Setup Flatpak
        run: |
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          sudo flatpak install -y flathub org.freedesktop.Platform//23.08 org.freedesktop.Sdk//23.08

      # Then setup Flutter and build
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.1'  # Updated to latest Flutter 3.29.1 version
          channel: 'stable'

      - name: Generate API Keys File
        run: |
          mkdir -p lib
          cat > lib/api_keys.dart << EOF
          /// API Keys for external services
          class ApiKeys {
            /// Spotify API Credentials
            static const String spotifyClientId = '${{ secrets.SPOTIFY_CLIENT_ID }}';
            static const String spotifyClientSecret = '${{ secrets.SPOTIFY_CLIENT_SECRET }}';
          }
          EOF

      - name: Build Flutter App
        run: |
          flutter config --enable-linux-desktop
          flutter doctor -v
          flutter pub get
          
          # Build Flutter app
          flutter build linux --release
          
          # Prepare icons - resize to 512x512 if needed
          mkdir -p icons
          convert assets/rateme.png -resize 512x512 icons/com.ali3nated0.rateme.png
          
          # Copy files to build directory
          rm -rf flatpak-build
          mkdir -p flatpak-build
          cp -r build/linux/x64/release/bundle/* flatpak-build/
          cp icons/com.ali3nated0.rateme.png flatpak-build/
          
          # Create desktop entry with correct icon name
          cat > flatpak-build/com.ali3nated0.rateme.desktop << EOF
          [Desktop Entry]
          Name=Rate Me!  # Add exclamation mark here
          Exec=rateme
          Icon=com.ali3nated0.rateme
          Type=Application
          Categories=Audio;Music;
          EOF

      - name: Create Flatpak Manifest
        run: |
          cat > com.ali3nated0.rateme.yml << EOF
          app-id: com.ali3nated0.rateme
          runtime: org.freedesktop.Platform
          runtime-version: '23.08'
          sdk: org.freedesktop.Sdk
          command: rateme
          finish-args:
            - --share=ipc
            - --socket=fallback-x11
            - --socket=wayland
            - --device=dri
            - --filesystem=home
            # Add share/system for glib
            - --env=GIO_EXTRA_MODULES=/app/lib/gio/modules
          modules:
            - name: rateme
              buildsystem: simple
              build-commands:
                - install -Dm755 rateme /app/bin/rateme
                - install -d /app/lib
                - cp -r lib/* /app/lib/
                - install -Dm644 com.ali3nated0.rateme.desktop /app/share/applications/${FLATPAK_ID}.desktop
                - install -Dm644 com.ali3nated0.rateme.png /app/share/icons/hicolor/512x512/apps/${FLATPAK_ID}.png
              sources:
                - type: dir
                  path: flatpak-build
              # Add glib dependency
              add-extensions:
                org.freedesktop.Platform.GL:
                  version: '23.08'
                  directory: lib/GL
                  subdirectories: true
                  no-autodownload: true
                  autodelete: false
                org.freedesktop.Platform.Timezones:
                  version: '23.08'
                  directory: share/zoneinfo
          EOF

      - name: Build Flatpak Package
        run: |
          echo "Building Flatpak..."
          flatpak-builder --force-clean --repo=repo build-flatpak com.ali3nated0.rateme.yml
          echo "Creating bundle..."
          flatpak build-bundle repo RateMe_${{ inputs.version }}.flatpak $FLATPAK_ID

      - name: Upload Flatpak Package
        uses: actions/upload-artifact@v4
        with:
          name: RateMe-Flatpak
          path: RateMe_${{ inputs.version }}.flatpak
