name: Flatpak Build

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

env:
  FLATPAK_ID: com.ali3nated0.rateme

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: rateme

      # Install all build dependencies first
      - name: Install Dependencies
        run: |
          sudo add-apt-repository -y ppa:flatpak/stable
          sudo apt-get update
          sudo apt-get install -y \
            flatpak \
            flatpak-builder \
            xz-utils \
            clang \
            cmake \
            ninja-build \
            pkg-config \
            libgtk-3-dev \
            liblzma-dev \
            libstdc++-12-dev \
            libglu1-mesa

      # Setup Flatpak first
      - name: Setup Flatpak
        run: |
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          sudo flatpak install -y flathub org.freedesktop.Platform//23.08 org.freedesktop.Sdk//23.08

      # Then setup Flutter and build
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'

      - name: Build Flutter App
        run: |
          flutter config --enable-linux-desktop
          flutter doctor -v
          flutter pub get
          flutter build linux --release
          
          # Verify build output
          echo "Checking build output..."
          ls -la build/linux/x64/release/bundle || exit 1
          
          # Create desktop entry file
          mkdir -p build/linux/x64/release/bundle
          cat > build/linux/x64/release/bundle/com.ali3nated0.rateme.desktop << EOF
          [Desktop Entry]
          Name=Rate Me
          Exec=rateme
          Icon=rateme
          Type=Application
          Categories=Audio;Music;
          EOF

          # Copy icon
          cp assets/rateme.png build/linux/x64/release/bundle/

      - name: Create Flatpak Manifest
        run: |
          # Debug directory structure
          echo "Current directory contents:"
          pwd
          ls -la
          echo "Bundle directory contents:"
          ls -la build/linux/x64/release/bundle/
          
          cat > com.ali3nated0.rateme.yml << EOF
          app-id: com.ali3nated0.rateme
          runtime: org.freedesktop.Platform
          runtime-version: '23.08'
          sdk: org.freedesktop.Sdk
          command: rateme
          finish-args:
            - --share=ipc
            - --socket=fallback-x11
            - --socket=wayland
            - --device=dri
            - --filesystem=home
          modules:
            - name: rateme
              buildsystem: simple
              build-commands:
                - cp -r . /app/
                - chmod +x /app/rateme
                - mkdir -p /app/share/applications /app/share/icons/hicolor/512x512/apps
                - cp rateme.png /app/share/icons/hicolor/512x512/apps/
                - cp com.ali3nated0.rateme.desktop /app/share/applications/
              sources:
                - type: dir
                  path: build/linux/x64/release/bundle
          EOF

      - name: Build Flatpak Package
        run: |
          echo "Building Flatpak..."
          flatpak-builder --force-clean --repo=repo build com.ali3nated0.rateme.yml
          echo "Creating bundle..."
          flatpak build-bundle repo RateMe_${{ inputs.version }}.flatpak $FLATPAK_ID

      - name: Upload Flatpak Package
        uses: actions/upload-artifact@v4
        with:
          name: RateMe-Flatpak
          path: RateMe_${{ inputs.version }}.flatpak
