name: Linux Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
          
      - name: Build and Package
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build libgtk-3-dev
          
          # Build Flutter
          flutter config --enable-linux-desktop
          flutter pub get
          flutter build linux --release
          
          # Create staging directory for packaging
          cd build/linux/x64/release
          mkdir -p staging/usr/bin
          mkdir -p staging/usr/lib
          mkdir -p staging/usr/share/applications
          mkdir -p staging/usr/share/icons/hicolor/512x512/apps
          
          # Copy files to staging
          cp intermediates_do_not_run/rateme staging/usr/bin/
          cp -r lib/* staging/usr/lib/
          cp ../../../../linux/runner/rateme.desktop staging/usr/share/applications/
          cp ../../../../assets/app-icon.png staging/usr/share/icons/hicolor/512x512/apps/rateme.png
          
          # Build package from staging
          DESTDIR=staging cpack -G DEB -V
          
      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: rateme-deb
          path: build/linux/x64/release/*.deb
