name: Linux Build

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GDK_BACKEND: x11
      DISPLAY: :99

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ninja-build \
            libgtk-3-dev \
            cmake \
            pkg-config \
            clang \
            libglib2.0-dev \
            xvfb

      - name: Start Xvfb
        run: |
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
          cache: true

      - name: Build and Package Linux
        run: |
          flutter clean
          flutter config --enable-linux-desktop
          flutter pub get
          flutter pub run flutter_launcher_icons
          
          # Asegurarnos de que el directorio assets existe y tiene la imagen
          ls -la assets/
          echo "Contenido del directorio assets:"
          pwd
          find . -name "app-icon.png"
          
          export GDK_BACKEND=x11
          flutter build linux --release
          cd build/linux/x64/release
          
          # Copiar assets necesarios
          mkdir -p ../../../../assets
          cp ../../../../assets/app-icon.png ../../../../assets/
          
          cpack -G DEB -V
          cpack -G RPM -V

      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: RateMe-deb
          path: build/linux/x64/release/rateme-1.0.0-Linux.deb

      - name: Upload RPM
        uses: actions/upload-artifact@v4
        with:
          name: RateMe-rpm
          path: build/linux/x64/release/rateme-1.0.0-Linux.rpm
