name: Linux Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
          
      - name: Build and Package
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build libgtk-3-dev
          
          # Ensure Flutter is ready
          flutter doctor -v
          flutter clean
          flutter config --enable-linux-desktop
          flutter pub get
          
          # Build Flutter part first
          cd linux
          mkdir -p build
          cd build
          cmake ..
          make
          
          # Now create the package
          cpack -G DEB -V
          
      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: rateme-deb
          path: linux/build/*.deb
