name: Linux Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
          
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ninja-build \
            libgtk-3-0 \
            libgtk-3-dev \
            libglu1-mesa \
            libglu1-mesa-dev \
            desktop-file-utils \
            python3-pip \
            libgdk-pixbuf2.0-dev \
            cmake \
            pkg-config
          sudo pip3 install appimage-builder

      - name: Build Flutter
        run: |
          flutter config --enable-linux-desktop
          flutter pub get
          flutter build linux --release

      - name: Create AppImage
        run: |
          # Create required directories
          mkdir -p AppDir
          # Run appimage-builder from project root
          cd $GITHUB_WORKSPACE
          appimage-builder --recipe linux/packaging/AppImageBuilder.yml --skip-tests

      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: RateMe-Linux
          path: '*.AppImage'
