name: Linux Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
          
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ninja-build \
            libgtk-3-0 \
            libgtk-3-dev \
            libglu1-mesa \
            libglu1-mesa-dev \
            cmake \
            pkg-config \
            fuse \
            appstream

      - name: Build Flutter
        run: |
          flutter config --enable-linux-desktop
          flutter pub get
          flutter build linux --release

      - name: Package AppDir
        run: |
          mkdir -p AppDir/usr/{bin,lib}
          mkdir -p AppDir/usr/share/applications
          mkdir -p AppDir/usr/share/icons/hicolor/256x256/apps
          mkdir -p AppDir/usr/share/metainfo
          
          cp -r build/linux/x64/release/bundle/* AppDir/usr/bin/
          cp linux/rateme.desktop AppDir/usr/share/applications/
          cp assets/app-icon.png AppDir/usr/share/icons/hicolor/256x256/apps/rateme.png

      - name: Download AppImage tools
        run: |
          wget -c "https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage"
          wget -c "https://github.com/linuxdeploy/linuxdeploy-plugin-gtk/releases/download/continuous/linuxdeploy-plugin-gtk-x86_64.AppImage"
          chmod +x linuxdeploy*.AppImage

      - name: Build AppImage
        env:
          VERBOSE: 1
        run: |
          # Get linuxdeploy and extract it
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy-x86_64.AppImage
          
          # Configure FUSE
          sudo modprobe fuse || true
          sudo chmod 666 /dev/fuse || true
          sudo chown root:$USER /dev/fuse || true
          
          # Run with debugging
          ./linuxdeploy-x86_64.AppImage --appdir AppDir -e AppDir/usr/bin/rateme -d AppDir/usr/share/applications/rateme.desktop -i AppDir/usr/share/icons/hicolor/256x256/apps/rateme.png --output appimage -v2

      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: RateMe-Linux
          path: RateMe*.AppImage
