name: Linux Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
          
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build libgtk-3-dev rpm
          # Install appimage-builder properly
          sudo apt-get install -y python3-pip
          sudo pip3 install appimage-builder

      - name: Build Flutter
        run: |
          flutter config --enable-linux-desktop
          flutter pub get
          flutter build linux --release

      - name: Build AppImage
        run: |
          # Use appimage-builder with our config
          appimage-builder --recipe linux/AppImageBuilder.yml --skip-test

      - name: Build DEB & RPM
        run: |
          cd build/linux/x64/release
          cmake -DCMAKE_INSTALL_PREFIX=/usr ../../../linux
          make
          cpack -G DEB
          cpack -G RPM

      - name: Upload Packages
        uses: actions/upload-artifact@v4
        with:
          name: linux-packages
          path: |
            *.AppImage
            build/linux/x64/release/*.deb
            build/linux/x64/release/*.rpm
