name: Linux Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
          
      - name: Build with CMake
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build libgtk-3-dev
          flutter config --enable-linux-desktop
          flutter build linux --release
          
          # Build e instalación con CMake
          mkdir -p build/linux/packaging
          cd build/linux/packaging
          cmake ../../../linux -DCMAKE_BUILD_TYPE=Release
          cmake --build .
          make install
          cpack -G DEB -V
          
      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: rateme-deb
          path: build/linux/packaging/*.deb
