name: Linux Build

on:
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.19.3'

jobs:
  build-appimage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            ninja-build \
            clang \
            pkg-config \
            libgtk-3-dev \
            liblzma-dev \
            libstdc++-12-dev \
            libsecret-1-dev \
            fuse

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Build App
        run: |
          flutter config --enable-linux-desktop
          flutter pub get
          flutter build linux --release

      - name: Create AppImage Structure
        run: |
          mkdir -p AppDir
          cp -r build/linux/x64/release/bundle/* AppDir/
          cp assets/app-icon.png AppDir/rateme.png
          
          cat > AppDir/AppRun << 'EOF'
          #!/bin/sh
          cd "$(dirname "$0")"
          exec ./rateme "$@"
          EOF
          chmod +x AppDir/AppRun
          
          cat > AppDir/rateme.desktop << EOF
          [Desktop Entry]
          Name=Rate Me
          Exec=rateme
          Icon=rateme
          Type=Application
          Categories=Audio;Music;
          EOF

      - name: Get AppImage Tool
        run: |
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage

      - name: Build AppImage
        run: |
          ARCH=x86_64 ./appimagetool-x86_64.AppImage AppDir RateMe.AppImage

      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: RateMe-AppImage
          path: RateMe.AppImage

  build-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            ninja-build \
            clang \
            pkg-config \
            libgtk-3-dev \
            libsecret-1-dev \
            dpkg-dev \
            debhelper \
            libglib2.0-dev \
            libglib2.0-0 \
            libgobject-2.0-0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Build App
        run: |
          flutter config --enable-linux-desktop
          flutter pub get
          flutter build linux --release

      - name: Create DEB Structure
        run: |
          PKGDIR=rateme_1.0.0-1_amd64
          
          # Debug: List all available libraries
          echo "Available libraries:"
          find /usr/lib/x86_64-linux-gnu -name "libglib*" -o -name "libgobject*"
          
          # Create directories
          mkdir -p $PKGDIR/DEBIAN
          mkdir -p $PKGDIR/usr/lib/rateme
          mkdir -p $PKGDIR/usr/bin
          mkdir -p $PKGDIR/usr/share/applications
          mkdir -p $PKGDIR/usr/share/icons/hicolor/256x256/apps

          # Copy application files
          cp -r build/linux/x64/release/bundle/* $PKGDIR/usr/lib/rateme/
          cp assets/app-icon.png $PKGDIR/usr/share/icons/hicolor/256x256/apps/rateme.png

          # Create launcher script with direct path
          cat > $PKGDIR/usr/bin/rateme << 'EOF'
          #!/bin/sh
          export LD_LIBRARY_PATH=/usr/lib/rateme:$LD_LIBRARY_PATH
          exec /usr/lib/rateme/rateme "$@"
          EOF
          chmod +x $PKGDIR/usr/bin/rateme

          # Create control file with corrected dependencies
          cat > $PKGDIR/DEBIAN/control << EOF
          Package: rateme
          Version: 1.0.0-1
          Architecture: amd64
          Maintainer: Eduardo Antonio Fortuny Ruvalcaba <eduardo.fortuny@outlook.com>
          Depends: libglib2.0-0 (>= 2.72.0),
            libgtk-3-0 (>= 3.24.0),
            libsecret-1-0,
            libc6,
            libstdc++6,
            libgobject-2.0-0
          Section: utils
          Priority: optional
          Description: Rate your music albums
           A Flutter application for rating and organizing your music collection.
          EOF

          # Create desktop entry
          cat > $PKGDIR/usr/share/applications/rateme.desktop << EOF
          [Desktop Entry]
          Name=Rate Me
          Exec=/usr/bin/rateme
          Icon=rateme
          Type=Application
          Categories=Audio;Music;
          EOF

      - name: Build DEB
        run: dpkg-deb --build rateme_1.0.0-1_amd64

      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: RateMe-DEB
          path: rateme_1.0.0-1_amd64.deb