name: Linux Build

on:
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.19.3'

jobs:
  build-appimage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            ninja-build \
            clang \
            pkg-config \
            libgtk-3-dev \
            liblzma-dev \
            libstdc++-12-dev \
            libsecret-1-dev \
            fuse

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Build App
        run: |
          flutter config --enable-linux-desktop
          flutter pub get
          flutter build linux --release --verbose
          
          echo "Build contents:"
          ls -R build/linux/x64/release/

      - name: Create AppImage Structure
        run: |
          mkdir -p AppDir
          cp -r build/linux/x64/release/bundle/* AppDir/
          cp assets/app-icon.png AppDir/rateme.png
          
          cat > AppDir/AppRun << 'EOF'
          #!/bin/sh
          cd "$(dirname "$0")"
          exec ./rateme "$@"
          EOF
          chmod +x AppDir/AppRun
          
          cat > AppDir/rateme.desktop << EOF
          [Desktop Entry]
          Name=Rate Me
          Exec=rateme
          Icon=rateme
          Type=Application
          Categories=Audio;Music;
          EOF

      - name: Get AppImage Tool
        run: |
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage

      - name: Build AppImage
        run: |
          ARCH=x86_64 ./appimagetool-x86_64.AppImage AppDir RateMe.AppImage

      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: RateMe-AppImage
          path: RateMe.AppImage