name: Linux Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
          
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ninja-build \
            libgtk-3-0 \
            libgtk-3-dev \
            libglu1-mesa \
            libglu1-mesa-dev \
            cmake \
            pkg-config \
            fuse3

      - name: Build Flutter
        run: |
          flutter config --enable-linux-desktop
          flutter pub get
          flutter build linux --release

      - name: Package AppImage
        run: |
          # Download appimagetool without FUSE
          wget -O appimagetool "https://github.com/AppImage/AppImageKit/releases/download/13/appimagetool-x86_64.AppImage"
          chmod +x appimagetool
          
          # Extract appimagetool to use it without FUSE
          ./appimagetool --appimage-extract
          mv squashfs-root appimagetool-dir
          
          # Create basic AppDir structure
          mkdir -p AppDir/usr/{bin,lib}
          mkdir -p AppDir/usr/share/{applications,icons/hicolor/256x256/apps}
          
          # Copy application files
          cp -r build/linux/x64/release/bundle/* AppDir/usr/bin/
          cp linux/rateme.desktop AppDir/usr/share/applications/
          cp assets/app-icon.png AppDir/usr/share/icons/hicolor/256x256/apps/rateme.png
          
          # Create AppImage without FUSE
          ./appimagetool-dir/AppRun AppDir RateMe.AppImage

      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: RateMe-Linux
          path: Rate_Me*.AppImage
