name: Linux Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
          
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ninja-build \
            libgtk-3-0 \
            libgtk-3-dev \
            libglu1-mesa \
            libglu1-mesa-dev \
            cmake \
            pkg-config \
            fuse3

      - name: Build Flutter
        run: |
          flutter config --enable-linux-desktop
          flutter pub get
          flutter build linux --release

      - name: Package AppDir
        run: |
          # Create AppDir structure
          mkdir -p AppDir/usr/bin
          mkdir -p AppDir/usr/share/applications
          mkdir -p AppDir/usr/share/icons/hicolor/256x256/apps
          
          # Copy application files
          cp -r build/linux/x64/release/bundle/* AppDir/usr/bin/
          cp linux/rateme.desktop AppDir/usr/share/applications/
          cp assets/app-icon.png AppDir/usr/share/icons/hicolor/256x256/apps/rateme.png

      - name: Build AppImage
        env:
          QMAKE: /usr/bin/qmake
        run: |
          wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
          chmod a+x linuxdeployqt-continuous-x86_64.AppImage
          export PATH="/usr/lib/x86_64-linux-gnu/qt5/bin:$PATH"
          export LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu/:$LD_LIBRARY_PATH"
          ./linuxdeployqt-continuous-x86_64.AppImage --appimage-extract-and-run AppDir/usr/share/applications/rateme.desktop -bundle-non-qt-libs -verbose=2

      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: RateMe-Linux
          path: RateMe*.AppImage
