name: Linux Build

on:
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.19.3'

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            dpkg-dev \
            debhelper \
            fakeroot \
            cmake \
            ninja-build \
            clang \
            pkg-config \
            libgtk-3-dev \
            liblzma-dev \
            libstdc++-12-dev \
            libblkid-dev

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Build App
        run: |
          flutter config --enable-linux-desktop
          flutter build linux --release

      - name: Create DEB Structure
        run: |
          mkdir -p debian/rateme/usr/bin
          mkdir -p debian/rateme/usr/share/applications
          mkdir -p debian/rateme/usr/share/icons/hicolor/256x256/apps
          
          # Copy files
          cp -r build/linux/x64/release/bundle/* debian/rateme/usr/bin/
          cp assets/app-icon.png debian/rateme/usr/share/icons/hicolor/256x256/apps/rateme.png
          
          # Set permissions
          chmod +x debian/rules
          chmod -R 755 debian/rateme/usr/bin/*

      - name: Build DEB Package
        run: |
          dpkg-buildpackage -us -uc -b
          mv ../rateme_*.deb ./RateMe.deb

      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: RateMe-DEB
          path: RateMe.deb
