name: Linux Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y ninja-build libgtk-3-dev
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
      - name: Build DEB
        run: |
          dart pub global activate flutter_distributor
          flutter_distributor package --platform linux --targets deb
      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: rateme-deb
          path: dist/**/*.deb
