name: Linux Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
          
      - name: Build and Package
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build libgtk-3-dev
          
          # Build Flutter
          flutter config --enable-linux-desktop
          flutter pub get
          flutter build linux --release
          
          # Build package in staging directory
          cd build/linux/x64/release
          mkdir -p debian
          cmake -DCMAKE_INSTALL_PREFIX=/usr ../../../linux
          make
          DESTDIR=debian cmake --install .
          cpack -G DEB
          
      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: rateme-deb
          path: build/linux/x64/release/*.deb
