---
# Workflow for building and releasing macOS DMG
name: macOS Build

on:
  workflow_dispatch:  # Esto permite ejecución manual desde la interfaz de GitHub
  # Ya no se ejecutará automáticamente con push/pull_request

env:
  FLUTTER_VERSION: '3.19.3'

jobs:
  build:
    name: Build macOS DMG
    runs-on: macos-latest
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          brew install create-dmg
          rm -f /usr/local/bin/pod
          brew install cocoapods
          brew link --overwrite cocoapods

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Fix path version
        run: |
          sed -i.bak 's/path: \^1.9.1/path: 1.9.0/' pubspec.yaml

      - name: Build macOS
        run: |
          flutter pub get
          flutter config --enable-macos-desktop
          # Generate icons for macOS
          flutter pub run flutter_launcher_icons:main -f pubspec.yaml
          flutter build macos --release

      - name: Install flutter_distributor
        run: dart pub global activate flutter_distributor

      - name: Build package
        run: flutter_distributor package --platform macos --targets dmg

      - name: Create DMG
        run: |
          cd build/macos/Build/Products/Release
          create-dmg \
            --volname "RateMe Installer" \
            --volicon "RateMe.app/Contents/Resources/AppIcon.icns" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --icon "RateMe.app" 200 190 \
            --hide-extension "RateMe.app" \
            --app-drop-link 600 185 \
            "RateMe.dmg" \
            "RateMe.app"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RateMe-macOS
          path: build/macos/Build/Products/Release/RateMe.dmg

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-dmg
          path: dist/**/*.dmg
