---
  # Workflow for building and releasing macOS DMG
  name: macOS Build
  
  on:
    workflow_dispatch:  # Esto permite ejecución manual desde la interfaz de GitHub
    # Ya no se ejecutará automáticamente con push/pull_request
  
  env:
    FLUTTER_VERSION: '3.19.3'
  
  jobs:
    build:
      name: Build macOS DMG
      runs-on: macos-latest
      permissions: write-all
  
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
  
        - name: Setup Flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: ${{ env.FLUTTER_VERSION }}
            channel: 'stable'
            cache: true

        - name: Install create-dmg
          run: |
            brew install create-dmg

        - name: Build and Package
          run: |
            # Show environment info
            flutter doctor -v
            which flutter
            flutter --version
            
            # Debug build first to check for issues
            flutter build macos --debug --verbose
            
            # If debug succeeds, try release
            flutter build macos --release --verbose --no-tree-shake-icons
            
            cd build/macos/Build/Products/Release
            echo "Build directory contents:"
            ls -la
            
            # Print Xcode build logs
            if [ -f "../../LastBuild.xcactivitylog" ]; then
              echo "Xcode build log:"
              cat "../../LastBuild.xcactivitylog"
            fi

        - name: Upload Debug Build
          if: failure()
          uses: actions/upload-artifact@v4
          with:
            name: debug-build-logs
            path: build/macos/Build/

        - name: Upload Release Build
          if: success()
          uses: actions/upload-artifact@v4
          with:
            name: RateMe-macOS
            path: build/macos/Build/Products/Release/rateme.app