---
  # Workflow for building and releasing macOS DMG
  name: macOS Build
  
  on:
    workflow_dispatch:  # This allows manual execution from GitHub interface
    # Will not run automatically on push/pull_request
  
  env:
    FLUTTER_VERSION: '3.19.3'
  
  jobs:
    build-macos:
      runs-on: macos-latest
  
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Create Self-Signed Certificate
          run: |
            # Create keychain for build
            security create-keychain -p github_actions build.keychain
            security default-keychain -s build.keychain
            security unlock-keychain -p github_actions build.keychain
            
            # Create development certificate
            CERT_NAME="RateMe Developer"
            echo "Creating self-signed certificate: $CERT_NAME"
            security create-certificate-authority \
              -c "$CERT_NAME" \
              -o /tmp/RateMe.keychain
            
            # Import certificate into keychain
            security import /tmp/RateMe.keychain -k build.keychain
  
        - name: Setup Flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: ${{ env.FLUTTER_VERSION }}
            channel: 'stable'
            cache: true

        - name: Build macOS App
          run: |
            flutter config --enable-macos-desktop
            flutter pub get
            flutter build macos --release

        - name: Create DMG
          run: |
            brew install create-dmg
            
            # Prepare distribution folder
            mkdir -p dist
            cp -r build/macos/Build/Products/Release/RateMe.app dist/
            
            # Create DMG installer
            create-dmg \
              --volname "RateMe" \
              --window-pos 200 120 \
              --window-size 800 450 \
              --icon-size 100 \
              --app-drop-link 600 185 \
              "RateMe.dmg" \
              "dist/"

        - name: Upload DMG
          uses: actions/upload-artifact@v4
          with:
            name: RateMe-DMG
            path: RateMe.dmg