name: macOS Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
          cache: true

      - name: Basic Build
        run: |
          flutter pub get
          flutter build macos --debug --no-tree-shake-icons
          
          cd build/macos/Build/Products/Debug
          zip -r RateMe-Debug.zip "Rate Me.app"

      - name: Upload App
        uses: actions/upload-artifact@v4
        with:
          name: RateMe-macOS-Debug
          path: build/macos/Build/Products/Debug/RateMe-Debug.zip
