---
# Workflow for building and releasing macOS DMG
name: macOS Build

on:
  push:
    branches:
      - rateme
  pull_request:
    branches:
      - rateme

env:
  FLUTTER_VERSION: '3.19.3'

jobs:
  build:
    name: Build macOS DMG
    runs-on: macos-13
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          brew install create-dmg
          brew install swift-format

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Configure Xcode
        run: |
          sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
          sudo xcodebuild -license accept
          defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES

      - name: Fix path version
        run: |
          sed -i.bak 's/path: \^1.9.1/path: 1.9.0/' pubspec.yaml
          cat pubspec.yaml | grep path

      - name: Build macOS
        run: |
          flutter config --enable-macos-desktop
          flutter pub get
          flutter pub run flutter_launcher_icons
          flutter build macos --release
          ls -la build/macos/Build/Products/Release/RateMe.app/Contents/MacOS/

      - name: Prepare for Distribution
        run: |
          cd build/macos/Build/Products/Release
          chmod +x RateMe.app/Contents/MacOS/*
          ln -sf /Applications Applications
          create-dmg \
            --volname "RateMe" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --app-drop-link 600 185 \
            --icon "RateMe.app" 200 190 \
            "RateMe.dmg" \
            "RateMe.app"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RateMe-macOS
          path: build/macos/Build/Products/Release/RateMe.dmg
