---
# Workflow for building and releasing macOS DMG
name: macOS Build

on:
  workflow_dispatch:  # Esto permite ejecución manual desde la interfaz de GitHub
  # Ya no se ejecutará automáticamente con push/pull_request

env:
  FLUTTER_VERSION: '3.19.3'

jobs:
  build:
    name: Build macOS DMG
    runs-on: macos-latest
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          brew install create-dmg
          rm -f /usr/local/bin/pod
          brew install cocoapods
          brew link --overwrite cocoapods

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Fix path version
        run: |
          sed -i.bak 's/path: \^1.9.1/path: 1.9.0/' pubspec.yaml

      - name: Create entitlements file
        run: |
          cat > macos/Runner/Release.entitlements << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>com.apple.security.app-sandbox</key>
              <true/>
              <key>com.apple.security.network.client</key>
              <true/>
          </dict>
          </plist>
          EOF

      - name: Update Info.plist
        run: |
          cat > macos/Runner/Info.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>CFBundleDevelopmentRegion</key>
              <string>$(DEVELOPMENT_LANGUAGE)</string>
              <key>CFBundleExecutable</key>
              <string>$(EXECUTABLE_NAME)</string>
              <key>CFBundleIconFile</key>
              <string></string>
              <key>CFBundleIdentifier</key>
              <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
              <key>CFBundleInfoDictionaryVersion</key>
              <string>6.0</string>
              <key>CFBundleName</key>
              <string>Rate Me</string>
              <key>CFBundlePackageType</key>
              <string>APPL</string>
              <key>CFBundleShortVersionString</key>
              <string>$(FLUTTER_BUILD_NAME)</string>
              <key>CFBundleVersion</key>
              <string>$(FLUTTER_BUILD_NUMBER)</string>
              <key>LSMinimumSystemVersion</key>
              <string>$(MACOSX_DEPLOYMENT_TARGET)</string>
              <key>NSHighResolutionCapable</key>
              <true/>
              <key>NSMainNibFile</key>
              <string>MainMenu</string>
              <key>NSPrincipalClass</key>
              <string>NSApplication</string>
          </dict>
          </plist>
          EOF

      - name: Build macOS
        run: |
          flutter pub get
          flutter config --enable-macos-desktop
          # Generate icons for macOS
          flutter pub run flutter_launcher_icons:main -f pubspec.yaml
          flutter build macos --release

      - name: Install flutter_distributor
        run: dart pub global activate flutter_distributor

      - name: Build package
        run: flutter_distributor package --platform macos --targets dmg

      - name: Create DMG
        run: |
          cd build/macos/Build/Products/Release
          create-dmg \
            --volname "Rate Me" \
            --volicon "../../../../../assets/rateme.icns" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --icon "Rate Me.app" 200 190 \
            --hide-extension "Rate Me.app" \
            --app-drop-link 600 185 \
            "RateMe.dmg" \
            "Rate Me.app"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RateMe-macOS
          path: build/macos/Build/Products/Release/RateMe.dmg

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-dmg
          path: dist/**/*.dmg
