name: macOS Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
          cache: true

      - name: Basic Build
        run: |
          # Enable macOS desktop explicitly
          flutter config --enable-macos-desktop || true
          flutter precache --macos
          flutter doctor -v
          
          # Build steps
          flutter pub get
          flutter clean
          flutter build macos --debug --no-tree-shake-icons
          
          cd build/macos/Build/Products/Debug
          echo "Directory contents:"
          ls -la
          
          if [ ! -d "Rate Me.app" ]; then
            echo "App bundle not found! Current directory:"
            pwd
            ls -la
            echo "Parent directory contents:"
            cd ..
            ls -la
            exit 1
          fi
          
          zip -r RateMe-Debug.zip "Rate Me.app"
          echo "Zip file created:"
          ls -la RateMe-Debug.zip

      - name: Upload App
        uses: actions/upload-artifact@v4
        with:
          name: RateMe-macOS-Debug
          path: build/macos/Build/Products/Debug/RateMe-Debug.zip
