name: macOS Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
          cache: true

      - name: Build macOS
        run: |
          flutter config --enable-macos-desktop
          flutter clean
          flutter pub get
          flutter build macos --release
          
      - name: Package DMG
        run: |
          cd build/macos/Build/Products/Release
          # Create DMG with simple hdiutil commands
          hdiutil create -format UDZO -srcfolder "Rate Me.app" -volname "Rate Me" RateMe.dmg
          ls -la RateMe.dmg

      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: RateMe-macOS
          path: build/macos/Build/Products/Release/RateMe.dmg
