---
  # Workflow for building and releasing macOS DMG
  name: macOS Build
  
  on:
    workflow_dispatch:  # Esto permite ejecución manual desde la interfaz de GitHub
    # Ya no se ejecutará automáticamente con push/pull_request
  
  env:
    FLUTTER_VERSION: '3.19.3'
  
  jobs:
    build:
      name: Build macOS DMG
      runs-on: macos-latest
      permissions: write-all
  
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
  
        - name: Setup Flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: ${{ env.FLUTTER_VERSION }}
            channel: 'stable'
            cache: true

        - name: Flutter Info
          run: |
            echo "Flutter version:"
            flutter --version
            echo "Flutter doctor:"
            flutter doctor -v
            echo "Flutter config:"
            flutter config

        - name: Build
          run: |
            # Build app
            flutter pub get
            flutter config --enable-macos-desktop
            flutter build macos --debug
            
            cd build/macos/Build/Products/Debug
            echo "Debug build contents:"
            ls -la
            
            APP_NAME=$(ls *.app)
            echo "Found app: $APP_NAME"

        - name: Package
          run: |
            cd build/macos/Build/Products/Debug
            zip -r RateMe-Debug.zip *.app

        - name: Upload
          uses: actions/upload-artifact@v4
          with:
            name: RateMe-macOS-Debug
            path: build/macos/Build/Products/Debug/RateMe-Debug.zip