name: macOS Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
          cache: true

      - name: Build App Bundle
        run: |
          flutter config --enable-macos-desktop
          
          # Configure build settings for universal binary
          plutil -replace MACOSX_DEPLOYMENT_TARGET -string "10.14" macos/Runner.xcodeproj/project.pbxproj
          
          # Build without signing
          cd macos
          sed -i '' 's/CODE_SIGN_IDENTITY = "Apple Development"/CODE_SIGN_IDENTITY = "-"/g' Runner.xcodeproj/project.pbxproj
          
          # Build for both architectures
          cd ..
          flutter clean
          flutter pub get
          flutter build macos --release --universal
          
          cd build/macos/Build/Products/Release
          echo "Contents of Release directory:"
          ls -la
          
          if [ ! -d "rateme.app" ]; then
            echo "Error: rateme.app not found!"
            exit 1
          fi
          
          # Create zip with verbose output
          ditto -v -c -k --sequesterRsrc --keepParent "rateme.app" "RateMe-Universal.zip"

      - name: Upload App
        uses: actions/upload-artifact@v4
        with:
          name: RateMe-macOS-Universal
          path: build/macos/Build/Products/Release/RateMe-Universal.zip
