name: macOS Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
          cache: true

      - name: Create entitlements file
        run: |
          cat > macos/Runner/Release.entitlements << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>com.apple.security.app-sandbox</key>
              <true/>
              <key>com.apple.security.network.client</key>
              <true/>
              <key>com.apple.security.files.user-selected.read-write</key>
              <true/>
          </dict>
          </plist>
          EOF

      - name: Install flutter_distributor
        run: dart pub global activate flutter_distributor

      - name: Build macOS
        run: |
          flutter pub get
          flutter config --enable-macos-desktop
          flutter build macos --release

      - name: Create DMG
        run: flutter_distributor package --platform macos --targets dmg

      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: RateMe-macOS
          path: dist/*/dmg/*.dmg
