---
  # Workflow for building and releasing macOS DMG
  name: macOS Build
  
  on:
    workflow_dispatch:  # Esto permite ejecución manual desde la interfaz de GitHub
    # Ya no se ejecutará automáticamente con push/pull_request
  
  env:
    FLUTTER_VERSION: '3.19.3'
  
  jobs:
    build:
      name: Build macOS DMG
      runs-on: macos-latest
      permissions: write-all
  
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
  
        - name: Setup Flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: ${{ env.FLUTTER_VERSION }}
            channel: 'stable'
            cache: true

        - name: Install create-dmg
          run: |
            brew install create-dmg

        - name: Build and Package
          run: |
            # Check Flutter configuration
            flutter doctor -v
            
            # Enable macOS desktop and verify
            flutter config --enable-macos-desktop
            flutter config
            
            # Build process
            flutter pub get
            flutter build macos --release --verbose
            
            cd build/macos/Build/Products/Release
            
            echo "Directory contents and permissions:"
            ls -la
            
            chmod -R +x rateme.app
            
            create-dmg \
              --volname "Rate Me" \
              --window-pos 200 120 \
              --window-size 800 400 \
              --icon-size 100 \
              --icon "rateme.app" 200 190 \
              --hide-extension "rateme.app" \
              --app-drop-link 600 185 \
              "RateMe.dmg" \
              "rateme.app"

        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: RateMe-macOS
            path: build/macos/Build/Products/Release/RateMe.dmg