name: macOS Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        type: string
        default: '1.0.0-1'
  workflow_call:
    inputs:
      version:
        required: true
        type: string
        description: 'Version number'

env:
  FLUTTER_VERSION: '3.29.1'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true # Add caching for better performance

      # Add cache for pub dependencies
      - name: Cache pub dependencies
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.PUB_CACHE }}
            .dart_tool/
          key: pub-dependencies-macos-${{ runner.os }}-${{ hashFiles('pubspec.lock') }}
          restore-keys: |
            pub-dependencies-macos-${{ runner.os }}-

      - name: Setup Build
        run: |
          # Install ImageMagick first
          brew install imagemagick
          
          # Download app icon
          mkdir -p assets
          curl -o assets/app-icon.png https://raw.githubusercontent.com/ALi3naTEd0/RateMe/main/assets/rateme.png

      # Keep the app icon generation part
      - name: Generate App Icons
        run: |
          # Generate app icons using magick instead of convert
          cd macos/Runner/Assets.xcassets/AppIcon.appiconset
          ls -la ../../../../assets/  # Debug: check if file exists
          magick ../../../../assets/app-icon.png -resize 16x16 app_icon_16.png
          magick ../../../../assets/app-icon.png -resize 32x32 app_icon_32.png
          magick ../../../../assets/app-icon.png -resize 64x64 app_icon_64.png
          magick ../../../../assets/app-icon.png -resize 128x128 app_icon_128.png
          magick ../../../../assets/app-icon.png -resize 256x256 app_icon_256.png
          magick ../../../../assets/app-icon.png -resize 512x512 app_icon_512.png
          magick ../../../../assets/app-icon.png -resize 1024x1024 app_icon_1024.png
          cd ../../../../

      # Install dependencies first to improve build performance
      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Configure macOS
        run: |
          flutter config --enable-macos-desktop
          
          # Fix bundle identifier and add required keys
          sed -i '' 's/com.example.rateme/com.alienated.rateme/g' macos/Runner.xcodeproj/project.pbxproj
          
          # Ensure Info.plist has required keys
          plutil -replace NSHighResolutionCapable -bool true macos/Runner/Info.plist
          plutil -replace NSSupportsAutomaticGraphicsSwitching -bool true macos/Runner/Info.plist

      - name: Build macOS App
        run: |
          # Disable Metal for better VM compatibility
          defaults write com.alienated.rateme GSSupportsMetal -bool NO
          defaults write com.alienated.rateme GSUseOpenGL -bool YES
          
          flutter build macos --release --no-pub # Add --no-pub flag for better performance

      - name: Create DMG
        run: |
          APP_NAME="RateMe"
          APP_DIR="build/macos/Build/Products/Release/$APP_NAME.app"
          DMG_DIR="$HOME/$APP_NAME-dmg"
          DMG_NAME="RateMe_${{ inputs.version || github.event.inputs.version }}.dmg"

          mkdir -p "$DMG_DIR"
          cp -r "$APP_DIR" "$DMG_DIR/"
          ln -s /Applications "$DMG_DIR/Applications"

          SetFile -a V "$DMG_DIR"

          hdiutil create -volname "$APP_NAME" -srcfolder "$DMG_DIR" -ov -format UDZO "$HOME/$DMG_NAME"

      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: RateMe-DMG
          path: ~/RateMe_${{ inputs.version || github.event.inputs.version }}.dmg