---
  # Workflow for building and releasing macOS DMG
  name: macOS Build
  
  on:
    workflow_dispatch:  # This allows manual execution from GitHub interface
    # Will not run automatically on push/pull_request
  
  env:
    FLUTTER_VERSION: '3.19.3'
  
  jobs:
    build-macos:
      runs-on: macos-latest
  
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Create Self-Signed Certificate
          run: |
            # Create keychain for build
            security create-keychain -p github_actions ~/Library/Keychains/build.keychain
            security default-keychain -s ~/Library/Keychains/build.keychain
            security unlock-keychain -p github_actions ~/Library/Keychains/build.keychain
            
            # Create self-signed certificate
            CERT_NAME="RateMe Developer"
            echo "Creating self-signed certificate: $CERT_NAME"
            
            # Generate certificate
            openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
              -keyout /tmp/RateMe.key -out /tmp/RateMe.crt \
              -subj "/CN=$CERT_NAME"
            
            # Convert to p12 format
            openssl pkcs12 -export \
              -in /tmp/RateMe.crt \
              -inkey /tmp/RateMe.key \
              -out /tmp/RateMe.p12 \
              -name "$CERT_NAME" \
              -passout pass:github_actions
            
            # Import into keychain
            security import /tmp/RateMe.p12 -k ~/Library/Keychains/build.keychain -P github_actions -T /usr/bin/codesign
  
        - name: Setup Flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: ${{ env.FLUTTER_VERSION }}
            channel: 'stable'
            cache: true

        - name: Build macOS App
          run: |
            flutter config --enable-macos-desktop
            flutter pub get
            flutter build macos --release

        - name: Create DMG
          run: |
            brew install create-dmg
            
            # Prepare distribution folder
            mkdir -p dist
            cp -r build/macos/Build/Products/Release/RateMe.app dist/
            
            # Create DMG installer
            create-dmg \
              --volname "RateMe" \
              --window-pos 200 120 \
              --window-size 800 450 \
              --icon-size 100 \
              --app-drop-link 600 185 \
              "RateMe.dmg" \
              "dist/"

        - name: Upload DMG
          uses: actions/upload-artifact@v4
          with:
            name: RateMe-DMG
            path: RateMe.dmg