---
  # Workflow for building and releasing macOS DMG
  name: macOS Build
  
  on:
    workflow_dispatch:  # This allows manual execution from GitHub interface
    # Will not run automatically on push/pull_request
  
  env:
    FLUTTER_VERSION: '3.19.3'
  
  jobs:
    build-dmg:
      runs-on: macos-latest
  
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Install Flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: ${{ env.FLUTTER_VERSION }}
            channel: 'stable'
            cache: true

        - name: Setup Build
          run: |
            flutter config --enable-macos-desktop
            flutter pub get
            
            # Fix bundle identifier and add required keys
            sed -i '' 's/com.example.rateme/com.alienated.rateme/g' macos/Runner.xcodeproj/project.pbxproj
            
            # Ensure Info.plist has required keys
            plutil -replace NSHighResolutionCapable -bool true macos/Runner/Info.plist
            plutil -replace NSSupportsAutomaticGraphicsSwitching -bool true macos/Runner/Info.plist

        - name: Build macOS App
          run: flutter build macos --release

        - name: Create DMG
          run: |
            APP_NAME="RateMe"
            APP_DIR="build/macos/Build/Products/Release/$APP_NAME.app"
            DMG_DIR="$HOME/$APP_NAME-dmg"
            DMG_NAME="$APP_NAME.dmg"

            # Create DMG structure
            mkdir -p "$DMG_DIR"
            cp -r "$APP_DIR" "$DMG_DIR/"

            # Create unsigned DMG
            hdiutil create -volname "$APP_NAME" -srcfolder "$DMG_DIR" -ov -format UDZO "$HOME/$DMG_NAME"

        - name: Upload DMG
          uses: actions/upload-artifact@v4
          with:
            name: RateMe-DMG
            path: ~/RateMe.dmg