---
  # Workflow for building and releasing macOS DMG
  name: macOS Build
  
  on:
    workflow_dispatch:  # Esto permite ejecución manual desde la interfaz de GitHub
    # Ya no se ejecutará automáticamente con push/pull_request
  
  env:
    FLUTTER_VERSION: '3.19.3'
  
  jobs:
    build:
      name: Build macOS DMG
      runs-on: macos-13
      permissions: write-all
  
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
  
        - name: Install build tools
          run: |
            # Update Homebrew and install dependencies
            brew update
            HOMEBREW_NO_AUTO_UPDATE=1 brew install create-dmg
            
            # Remove and reinstall cocoapods avoiding conflicts
            brew uninstall --ignore-dependencies cocoapods || true
            brew cleanup
            gem uninstall -aIx cocoapods || true
            gem install cocoapods -v 1.13.0
            pod setup
  
        - name: Setup Flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: ${{ env.FLUTTER_VERSION }}
            channel: 'stable'
            cache: true
  
        - name: Fix path version
          run: |
            sed -i.bak 's/path: \^1.9.1/path: 1.9.0/' pubspec.yaml
  
        - name: Generate App Icons
          run: |
            mkdir -p macos/Runner/Assets.xcassets/AppIcon.appiconset
  
        - name: Build macOS
          run: |
            flutter pub get
            flutter config --enable-macos-desktop
            flutter pub run flutter_launcher_icons:main -f pubspec.yaml
            flutter build macos --release
            
            # Verify app name and contents
            cd build/macos/Build/Products/Release
            echo "Directory contents:"
            ls -la
  
        - name: Create DMG
          run: |
            cd build/macos/Build/Products/Release
            
            # Show exact app name
            APP_NAME=$(ls *.app)
            echo "Found app: $APP_NAME"
            
            create-dmg \
              --volname "Rate Me" \
              --window-pos 200 120 \
              --window-size 800 400 \
              --icon-size 100 \
              --icon "$APP_NAME" 200 190 \
              --app-drop-link 600 185 \
              "RateMe.dmg" \
              "$APP_NAME"
  
        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: RateMe-macOS
            path: build/macos/Build/Products/Release/RateMe.dmg