name: macOS Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
          cache: true

      - name: Build App Bundle
        run: |
          flutter config --enable-macos-desktop
          
          # Modify Xcode build settings
          cd macos
          sed -i '' 's/CODE_SIGN_IDENTITY = "Apple Development"/CODE_SIGN_IDENTITY = "-"/g' Runner.xcodeproj/project.pbxproj
          
          # Build without signing
          cd ..
          flutter clean
          flutter pub get
          flutter build macos --debug \
            --dart-define=FLUTTER_BUILD_MODE=debug \
            --build-name=1.0.0 \
            --build-number=1
          
          cd build/macos/Build/Products/Debug
          echo "Contents of Debug directory:"
          ls -la
          
          if [ ! -d "Rate Me.app" ]; then
            echo "Error: Rate Me.app not found!"
            echo "Contents of parent directory:"
            cd ..
            ls -la
            exit 1
          fi
          
          # Create zip with verbose output
          ditto -v -c -k --sequesterRsrc --keepParent "Rate Me.app" "RateMe-Debug.zip"
          
          echo "Created zip file:"
          ls -la RateMe-Debug.zip

      - name: Upload App
        uses: actions/upload-artifact@v4
        with:
          name: RateMe-macOS-Debug
          path: build/macos/Build/Products/Debug/RateMe-Debug.zip
