---
  # Workflow for building and releasing macOS DMG
  name: macOS Build
  
  on:
    workflow_dispatch:  # Esto permite ejecución manual desde la interfaz de GitHub
    # Ya no se ejecutará automáticamente con push/pull_request
  
  env:
    FLUTTER_VERSION: '3.19.3'
  
  jobs:
    build:
      name: Build macOS DMG
      runs-on: macos-latest
      permissions: write-all
  
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
  
        - name: Setup Flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: ${{ env.FLUTTER_VERSION }}
            channel: 'stable'
            cache: true

        - name: Build and Package
          run: |
            flutter doctor -v
            flutter config --enable-macos-desktop
            flutter pub get
            flutter build macos --release --verbose
            
            cd build/macos/Build/Products/Release
            pwd
            ls -la
            find . -name "*.app"

        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: RateMe-macOS
            path: |
              build/macos/Build/Products/Release/*.app