name: macOS Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
          cache: true

      - name: Build App Bundle
        env:
          MACOSX_DEPLOYMENT_TARGET: "10.14"
        run: |
          flutter config --enable-macos-desktop
          
          # Configure build settings
          cd macos
          plutil -replace MACOSX_DEPLOYMENT_TARGET -string "10.14" Runner.xcodeproj/project.pbxproj
          plutil -replace ONLY_ACTIVE_ARCH -string "NO" Runner.xcodeproj/project.pbxproj
          plutil -replace ENABLE_BITCODE -string "NO" Runner.xcodeproj/project.pbxproj
          plutil -replace CODE_SIGNING_REQUIRED -string "NO" Runner.xcodeproj/project.pbxproj
          plutil -replace CODE_SIGNING_ALLOWED -string "NO" Runner.xcodeproj/project.pbxproj
          plutil -replace CODE_SIGN_IDENTITY -string "-" Runner.xcodeproj/project.pbxproj
          
          cd ..
          flutter clean
          flutter pub get
          
          # Build for both architectures
          flutter build macos --release \
            --dart-define=FLUTTER_BUILD_NAME=1.0.0 \
            --dart-define=FLUTTER_BUILD_NUMBER=1
          
          cd build/macos/Build/Products/Release
          
          # Create zip with verbose output
          ditto -v -c -k --sequesterRsrc --keepParent "rateme.app" "RateMe-Universal.zip"

      - name: Upload App
        uses: actions/upload-artifact@v4
        with:
          name: RateMe-macOS-Universal
          path: build/macos/Build/Products/Release/RateMe-Universal.zip
