name: macOS Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
          cache: true

      - name: Build App Bundle
        run: |
          flutter config --enable-macos-desktop
          flutter clean
          flutter pub get
          
          # Build without signing and with debug symbols
          flutter build macos --debug --no-codesign
          
          cd build/macos/Build/Products/Debug
          # Create a zip instead of DMG for testing
          ditto -c -k --sequesterRsrc --keepParent "Rate Me.app" "RateMe-Debug.zip"

      - name: Upload App
        uses: actions/upload-artifact@v4
        with:
          name: RateMe-macOS-Debug
          path: build/macos/Build/Products/Debug/RateMe-Debug.zip
