name: macOS Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
          cache: true

      - name: Build App Bundle
        env:
          DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
          MACOSX_DEPLOYMENT_TARGET: "10.14"
        run: |
          # Setup architectures
          echo "Setting up build environment..."
          defaults write com.apple.dt.Xcode IDEBuildOperationMaxNumberOfConcurrentCompileTasks 4
          
          # Enable desktop builds
          flutter config --enable-macos-desktop
          
          # Clean and get dependencies
          flutter clean
          flutter pub get
          
          # Build universal binary
          echo "Building universal binary..."
          flutter build macos \
            --release \
            --no-codesign \
            --dart-define=FLUTTER_BUILD_NAME=1.0.0 \
            --dart-define=FLUTTER_BUILD_NUMBER=1
          
          echo "Checking build output..."
          cd build/macos/Build/Products/Release
          ls -la
          
          # Create zip with verbose output
          ditto -v -c -k --sequesterRsrc --keepParent "Rate Me.app" "RateMe-Universal.zip"

      - name: Upload App
        uses: actions/upload-artifact@v4
        with:
          name: RateMe-macOS-Universal
          path: build/macos/Build/Products/Release/RateMe-Universal.zip
