---
# Workflow for building and releasing macOS DMG
name: macOS Build

on:
  push:
    branches:
      - rateme
  pull_request:
    branches:
      - rateme

env:
  FLUTTER_VERSION: '3.19.3'

jobs:
  build:
    name: Build macOS DMG
    runs-on: macos-latest
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Temporarily modify path version for macOS
        run: |
          sed -i.bak 's/path: \^1.9.1/path: 1.9.0/' pubspec.yaml
          cat pubspec.yaml | grep path

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Install create-dmg
        run: brew install create-dmg

      - name: Disable macOS Code Signing
        run: |
          sudo defaults write com.apple.dt.Xcode DisableAutomaticCodeSigning -bool YES
          sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

      - name: Build macOS
        run: |
          flutter config --enable-macos-desktop
          flutter pub get
          flutter pub run flutter_launcher_icons
          flutter build macos --no-codesign
          ls -la build/macos/Build/Products/Release/RateMe.app/Contents/MacOS/

      - name: Create DMG
        run: |
          ln -sf /Applications "build/macos/Build/Products/Release/Applications"
          create-dmg \
            --volname "RateMe" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --app-drop-link 600 185 \
            --icon "RateMe.app" 200 190 \
            "RateMe.dmg" \
            "build/macos/Build/Products/Release/RateMe.app"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RateMe-macOS
          path: RateMe.dmg
