---
# Workflow for building and releasing macOS DMG
name: macOS Build

"on":
  push:
    branches:
      - rateme
  pull_request:
    branches:
      - rateme

jobs:
  build:
    name: Build macOS DMG
    runs-on: macos-latest
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Temporarily modify path version for macOS
        run: |
          sed -i.bak 's/path: \^1.9.1/path: 1.9.0/' pubspec.yaml
          cat pubspec.yaml | grep path

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.19.3'  # Use newer Flutter version that supports path 1.9.1
          cache: true
          cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash
          cache-path: ${{ runner.tool_cache }}/flutter/cache

      - name: Enable macOS
        run: flutter config --enable-macos-desktop

      - name: Debug Info
        run: |
          pwd
          ls -la
          flutter --version
          flutter doctor -v
          flutter config

      - name: Install create-dmg
        run: |
          brew update
          brew install create-dmg
          create-dmg --version

      - name: Install dependencies
        run: flutter pub get

      - name: Generate icons
        run: flutter pub run flutter_launcher_icons

      - name: Build macOS
        run: |
          flutter build macos --release
          ls -la build/macos/Build/Products/Release/RateMe.app/Contents/
          ls -la build/macos/Build/Products/Release/RateMe.app/Contents/Resources/
          ls -la build/macos/Build/Products/Release/RateMe.app/Contents/Frameworks/
          # Verificar permisos
          codesign --verify -vvvv build/macos/Build/Products/Release/RateMe.app
          # Verificar que la app sea ejecutable
          chmod +x build/macos/Build/Products/Release/RateMe.app/Contents/MacOS/rateme

      - name: Create DMG
        run: |
          create-dmg \
            --volname "RateMe" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --icon "RateMe.app" 200 190 \
            --hide-extension "RateMe.app" \
            --app-drop-link 600 185 \
            "RateMe.dmg" \
            "build/macos/Build/Products/Release/RateMe.app"

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: RateMe-macOS
          path: RateMe.dmg
