---
  # Workflow for building and releasing macOS DMG
  name: macOS Build
  
  on:
    workflow_dispatch:  # Esto permite ejecución manual desde la interfaz de GitHub
    # Ya no se ejecutará automáticamente con push/pull_request
  
  env:
    FLUTTER_VERSION: '3.19.3'
  
  jobs:
    build:
      name: Build macOS DMG
      runs-on: macos-13
      permissions: write-all
  
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
  
        - name: Install build tools
          run: |
            brew install create-dmg
            rm -f /usr/local/bin/pod
            brew install cocoapods
            brew link --overwrite cocoapods
  
        - name: Setup Flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: ${{ env.FLUTTER_VERSION }}
            channel: 'stable'
            cache: true
  
        - name: Fix path version
          run: |
            sed -i.bak 's/path: \^1.9.1/path: 1.9.0/' pubspec.yaml
  
        - name: Generate Icons
          run: |
            wget -O icon.png "https://raw.githubusercontent.com/ALi3naTEd0/RateMe/rateme/assets/icon.png"
            mkdir -p macos/Runner/Assets.xcassets/AppIcon.appiconset
            
            # Generate different sizes
            for size in 16 32 64 128 256 512 1024; do
              sips -z $size $size icon.png --out macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_${size}.png
            done
  
        - name: Build macOS
          run: |
            flutter pub get
            flutter config --enable-macos-desktop
            flutter build macos --release
  
        - name: Create DMG
          run: |
            cd build/macos/Build/Products/Release
            create-dmg \
              --volname "RateMe" \
              --window-pos 200 120 \
              --window-size 800 400 \
              --icon-size 100 \
              --icon "Rate Me.app" 200 190 \
              --app-drop-link 600 185 \
              "RateMe.dmg" \
              "Rate Me.app"
  
        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: RateMe-macOS
            path: build/macos/Build/Products/Release/RateMe.dmg