name: macOS Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
          cache: true

      - name: Configure macOS build
        run: |
          defaults write com.apple.security.xcbuildsystem.allownetworkbuild -bool true
          defaults write com.apple.security.temporary-exception.files.absolute-path.read-write -bool true

      - name: Build and Package
        run: |
          flutter config --enable-macos-desktop
          flutter clean
          flutter pub get
          flutter build macos --release --no-codesign
          
          cd build/macos/Build/Products/Release
          
          # Create temp directory for DMG
          mkdir -p "RateMe"
          cp -R "Rate Me.app" "RateMe/"
          ln -s /Applications "RateMe/Applications"
          
          # Create DMG without codesigning
          hdiutil create -volname "Rate Me" -srcfolder "RateMe" -ov -format UDZO "RateMe.dmg"

      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: RateMe-macOS
          path: build/macos/Build/Products/Release/RateMe.dmg
