name: macOS Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
          cache: true

      - name: Build App Bundle
        run: |
          flutter config --enable-macos-desktop
          flutter clean
          flutter pub get
          flutter build macos --release
          
          cd build/macos/Build/Products/Release
          
          # Create zip with verbose output
          ditto -v -c -k --sequesterRsrc --keepParent "rateme.app" "RateMe-Universal.zip"

      - name: Upload App
        uses: actions/upload-artifact@v4
        with:
          name: RateMe-macOS-Universal
          path: build/macos/Build/Products/Release/RateMe-Universal.zip
