---
  # Workflow for building and releasing macOS DMG
  name: macOS Build
  
  on:
    workflow_dispatch:  # Esto permite ejecución manual desde la interfaz de GitHub
    # Ya no se ejecutará automáticamente con push/pull_request
  
  env:
    FLUTTER_VERSION: '3.19.3'
  
  jobs:
    build:
      name: Build macOS DMG
      runs-on: macos-latest
      permissions: write-all
  
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
  
        - name: Setup Flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: ${{ env.FLUTTER_VERSION }}
            channel: 'stable'
            cache: true

        - name: Debug Environment
          run: |
            echo "Current directory:"
            pwd
            echo "Directory contents:"
            ls -la
            echo "Flutter config:"
            flutter config
            echo "Flutter doctor:"
            flutter doctor -v

        - name: Build Debug
          run: |
            flutter clean
            flutter pub get
            flutter config --enable-macos-desktop
            flutter build macos --debug
            
            echo "Build directory contents:"
            cd build/macos/Build/Products/Debug
            ls -la
            
            if [ ! -d "rateme.app" ]; then
              echo "App not found in expected location"
              echo "Searching for app bundle:"
              find ../../../.. -name "*.app" -type d
              exit 1

        - name: Upload Debug Build
          uses: actions/upload-artifact@v4
          with:
            name: RateMe-macOS-Debug
            path: build/macos/Build/Products/Debug/rateme.app