name: GitHub Pages

on:
  push:
    branches: ["rateme"]
    paths:
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Create favicon.html test page
        run: |
          cat > docs/favicon-test.html <<EOL
          <!DOCTYPE html>
          <html>
          <head>
            <title>Favicon Test</title>
            <link rel="icon" href="favicon.ico" type="image/x-icon">
          </head>
          <body>
            <h1>Favicon Test Page</h1>
            <p>If you can see the favicon in your browser tab, it's working!</p>
            <p><a href="index.html">Return to main page</a></p>
          </body>
          </html>
          EOL
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './docs'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
