name: GitHub Pages

# Solo se ejecuta en cambios manuales para evitar duplicación con pages-build-deployment
on:
  workflow_dispatch:

# Removemos los permisos que ya tiene pages-build-deployment
permissions:
  contents: read

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Copy files
        run: |
          mkdir -p docs/images
          # Asegurarse de que todos los archivos necesarios estén en su lugar
          echo "Directory structure:"
          ls -la docs/

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/
          git commit -m "Prepare content for GitHub Pages [skip ci]" || echo "No changes to commit"
          git push || echo "No changes to push"
