# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["rateme"]
    paths:
      - 'docs/**'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Prepare images
        run: |
          mkdir -p docs/images
          
          # Copy main app icon (using the correct path)
          if [ -f "assets/app-icon.png" ]; then
            echo "Using local app-icon.png"
            cp -f assets/app-icon.png docs/images/rateme.png
          elif [ -f "assets/rateme.png" ]; then
            echo "Using local rateme.png"
            cp -f assets/rateme.png docs/images/rateme.png
          else
            echo "Downloading app icon from GitHub"
            curl -o docs/images/rateme.png https://raw.githubusercontent.com/ALi3naTEd0/RateMe/rateme/assets/app-icon.png || \
            curl -o docs/images/rateme.png https://raw.githubusercontent.com/ALi3naTEd0/RateMe/rateme/assets/rateme.png
          fi
          
          # Create placeholders for screenshots if they don't exist
          [ ! -f docs/images/screenshot1.png ] && cp docs/images/rateme.png docs/images/screenshot1.png || true
          [ ! -f docs/images/screenshot2.png ] && cp docs/images/rateme.png docs/images/screenshot2.png || true
          [ ! -f docs/images/screenshot3.png ] && cp docs/images/rateme.png docs/images/screenshot3.png || true
          [ ! -f docs/images/hero-app.png ] && cp docs/images/rateme.png docs/images/hero-app.png || true
          
          # Install ImageMagick and create favicon
          sudo apt-get update && sudo apt-get install -y imagemagick
          convert docs/images/rateme.png docs/images/favicon.ico || true
          
          echo "Images prepared successfully:"
          ls -la docs/images/
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './docs'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
