name: Release Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to build"
        required: true
        default: "1.0.0-1"

jobs:
  android-build:
    uses: ALi3naTEd0/RateMe/.github/workflows/android.yml@rateme
    secrets: inherit
    with:
      version: ${{ github.event.inputs.version }}

  linux-build:
    needs: android-build
    uses: ALi3naTEd0/RateMe/.github/workflows/linux.yml@rateme
    secrets: inherit
    with:
      version: ${{ github.event.inputs.version }}

  windows-build:
    needs: linux-build
    uses: ALi3naTEd0/RateMe/.github/workflows/windows.yml@rateme
    secrets: inherit
    with:
      version: ${{ github.event.inputs.version }}

  macos-build:
    needs: windows-build
    uses: ALi3naTEd0/RateMe/.github/workflows/macos.yml@rateme
    secrets: inherit
    with:
      version: ${{ github.event.inputs.version }}

  create-release:
    needs: [android-build, linux-build, windows-build, macos-build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create dist directory
        run: mkdir -p dist

      - uses: actions/download-artifact@v4
        with:
          pattern: |
            rateme-universal
            rateme-AppImage
            RateMe-DMG
            RateMe-Setup
            RateMe-Portable
            rateme-DEB
            rateme-RPM
          path: dist

      - name: List dist contents
        run: |
          echo "Contents of dist directory:"
          ls -la dist
          echo "All artifacts downloaded:"
          find dist -type f
          
      - name: Prepare Release Files
        run: |
          cd dist || exit 1
          echo "Moving files from subdirectories..."
          for d in */; do
            if [ -d "$d" ]; then
              echo "Processing directory: $d"
              cp -v $d/* ./ || echo "Warning: Copy from $d failed"
            fi
          done
          echo "Final contents:"
          ls -la
          
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          draft: true
          files: dist/*
