name: Release Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to build"
        required: true
        default: "1.0.0-1"

jobs:
  android-build:
    uses: ALi3naTEd0/RateMe/.github/workflows/android.yml@rateme
    secrets: inherit
    with:
      version: ${{ github.event.inputs.version }}

  linux-build:
    needs: android-build
    uses: ALi3naTEd0/RateMe/.github/workflows/linux.yml@rateme
    secrets: inherit
    with:
      version: ${{ github.event.inputs.version }}

  windows-build:
    needs: linux-build
    uses: ALi3naTEd0/RateMe/.github/workflows/windows.yml@rateme
    secrets: inherit
    with:
      version: ${{ github.event.inputs.version }}

  macos-build:
    needs: windows-build
    uses: ALi3naTEd0/RateMe/.github/workflows/macos.yml@rateme
    secrets: inherit
    with:
      version: ${{ github.event.inputs.version }}

  create-release:
    needs: [android-build, linux-build, windows-build, macos-build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: |
            rateme-universal
            rateme-AppImage
            RateMe-DMG
            RateMe-Setup
            RateMe-Portable
            rateme-DEB
            rateme-RPM
          path: dist
          
      - name: Extract Artifacts
        run: |
          cd dist
          # Extraer todos los ZIPs
          find . -name "*.zip" -exec unzip -o {} -d ./extracted/ \;
          
          # Mover todos los archivos no-zip al directorio extracted
          find . -type f ! -name "*.zip" -exec cp {} ./extracted/ \;
          
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          draft: true
          files: dist/extracted/**/*
