name: Release Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to build"
        required: true
        type: string
        default: "1.0.0-1"
  push:
    tags:
      - 'v*'  # matches any version tag starting with 'v'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Get version
        id: get_version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          fi

      - name: Debug commit info
        run: |
          echo "Trigger commit SHA: ${{ github.sha }}"
          echo "Commit message: $(git log -1 --pretty=%B)"
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          commitish: ${{ github.sha }}

      - name: Trigger Documentation Update
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Update Documentation
          token: ${{ secrets.GITHUB_TOKEN }}
