name: Release Build

on:
  push:
    tags:
      - 'v*'  # matches any version tag starting with 'v'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false

      - name: Trigger Documentation Update
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Update Documentation
          token: ${{ secrets.GITHUB_TOKEN }}
