name: Release Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to build"
        required: true
        default: "1.0.0-1"
      platforms:
        description: "Platforms to build"
        required: true
        type: choice
        options:
          - all
          - android
          - linux
          - flatpak
          - windows
          - macos
      release_type:
        description: "Release type"
        required: true
        type: choice
        options:
          - draft
          - release
        default: 'draft'
  push:
    tags:
      - 'v*'  # matches any version tag starting with 'v'

permissions:
  contents: write

jobs:
  # STEP 1: BUILD PHASE - Build all required platforms
  android-build:
    if: |
      (github.event_name == 'workflow_dispatch' && (inputs.platforms == 'all' || inputs.platforms == 'android')) ||
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))
    uses: ALi3naTEd0/RateMe/.github/workflows/android.yml@rateme
    secrets: inherit
    with:
      version: ${{ github.event_name == 'workflow_dispatch' && inputs.version || github.ref_name }}

  linux-build:
    if: |
      (github.event_name == 'workflow_dispatch' && (inputs.platforms == 'all' || inputs.platforms == 'linux')) ||
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))
    uses: ALi3naTEd0/RateMe/.github/workflows/linux.yml@rateme
    secrets: inherit
    with:
      version: ${{ github.event_name == 'workflow_dispatch' && inputs.version || github.ref_name }}

  windows-build:
    if: |
      (github.event_name == 'workflow_dispatch' && (inputs.platforms == 'all' || inputs.platforms == 'windows')) ||
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))
    uses: ALi3naTEd0/RateMe/.github/workflows/windows.yml@rateme
    secrets: inherit
    with:
      version: ${{ github.event_name == 'workflow_dispatch' && inputs.version || github.ref_name }}

  macos-build:
    if: |
      (github.event_name == 'workflow_dispatch' && (inputs.platforms == 'all' || inputs.platforms == 'macos')) ||
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))
    uses: ALi3naTEd0/RateMe/.github/workflows/macos.yml@rateme
    secrets: inherit
    with:
      version: ${{ github.event_name == 'workflow_dispatch' && inputs.version || github.ref_name }}

  flatpak-build:
    if: |
      (github.event_name == 'workflow_dispatch' && (inputs.platforms == 'all' || inputs.platforms == 'flatpak')) ||
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))
    uses: ALi3naTEd0/RateMe/.github/workflows/flatpak.yml@rateme
    with:
      version: ${{ github.event_name == 'workflow_dispatch' && inputs.version || github.ref_name }}

  # STEP 2: CREATE RELEASE - Create the GitHub release and attach artifacts
  create-release:
    name: Create Release
    needs: [android-build, linux-build, windows-build, macos-build, flatpak-build]
    if: |
      !cancelled() && !failure() &&
      (needs.android-build.result == 'success' || needs.android-build.result == 'skipped') &&
      (needs.linux-build.result == 'success' || needs.linux-build.result == 'skipped') &&
      (needs.windows-build.result == 'success' || needs.windows-build.result == 'skipped') &&
      (needs.macos-build.result == 'success' || needs.macos-build.result == 'skipped') &&
      (needs.flatpak-build.result == 'success' || needs.flatpak-build.result == 'skipped')
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
      release_url: ${{ steps.set_release_url.outputs.url }}
    steps:
      - name: Get Version
        id: get_version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> "$GITHUB_OUTPUT"
          else
            echo "VERSION=${GITHUB_REF#refs/tags/v}" >> "$GITHUB_OUTPUT"
          fi
          echo "Using version: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version || github.ref_name }}"

      - name: Create Dist Directory
        run: mkdir -p dist

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: '**/*'
          merge-multiple: true

      - name: Organize Artifacts
        run: |
          echo "Initial dist content:"
          ls -la dist/
          
          # Move nested files to root
          find dist -mindepth 2 -type f -exec mv -t dist/ {} +
          
          # Remove empty directories
          find dist -type d -empty -delete
          
          echo "Final dist content:"
          ls -lh dist/

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: |
            RateMe-*       # Keep this format, don't change to 'rateme-*'
            !RateMe-*-symbols

      - name: Prepare release files
        run: |
          mkdir release
          find dist -type f -name "RateMe_*" -exec cp {} release/ \;
          cd release && ls -la

      # Replace the deprecated actions/create-release and use only softprops/action-gh-release
      - name: Create Release and Upload Assets
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event_name == 'workflow_dispatch' && format('v{0}', github.event.inputs.version) || github.ref }}
          name: Release v${{ steps.get_version.outputs.VERSION }}
          files: |
            dist/rateme_*_amd64.deb          # Changed from RateMe_*
            dist/rateme_*_x86_64.rpm
            dist/rateme_*.AppImage
            dist/rateme_*.flatpak
            dist/rateme_*_nixos.tar.gz
            dist/rateme_*_source.tar.gz
            dist/rateme_*.exe
            dist/rateme_*.dmg
            dist/rateme_*.apk
            dist/rateme_*_arm64-v8a.apk
            dist/rateme_*_armeabi-v7a.apk
            dist/rateme_*_x86_64.apk
            dist/rateme-portable.zip
          draft: ${{ github.event.inputs.release_type == 'draft' || github.event_name != 'workflow_dispatch' }}
          prerelease: false
          fail_on_unmatched_files: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set Release URL
        id: set_release_url
        run: |
          REPO_OWNER="${GITHUB_REPOSITORY_OWNER}"
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          VERSION="${{ steps.get_version.outputs.VERSION }}"
          TAG_NAME="${{ github.event_name == 'workflow_dispatch' && format('v{0}', github.event.inputs.version) || github.ref_name }}"
          RELEASE_URL="https://github.com/${REPO_OWNER}/${REPO_NAME}/releases/tag/${TAG_NAME}"
          echo "Setting release URL to: $RELEASE_URL"
          echo "url=$RELEASE_URL" >> "$GITHUB_OUTPUT"
          
      - name: Debug Release Info
        run: |
          echo "Release created successfully:"
          echo "Version: ${{ steps.get_version.outputs.VERSION }}"
          echo "URL: ${{ steps.set_release_url.outputs.url }}"

  # STEP 3: UPDATE DOCUMENTATION - Update docs with new version links
  update-docs:
    name: Update Documentation
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for changelog
          ref: rateme     # Main branch
          
      - name: Update Documentation
        run: |
          VERSION="${{ needs.create-release.outputs.version }}"
          
          # Update version numbers and download links in README
          sed -i "s|/download/v[0-9]\+\.[0-9]\+\.[0-9]\+-[0-9]\+/|/download/v${VERSION}/|g" README.md
          
          # Update standard file patterns
          sed -i "s|RateMe_[0-9]\+\.[0-9]\+\.[0-9]\+-[0-9]\+\.exe|RateMe_${VERSION}.exe|g" README.md
          sed -i "s|RateMe_[0-9]\+\.[0-9]\+\.[0-9]\+-[0-9]\+\.dmg|RateMe_${VERSION}.dmg|g" README.md
          sed -i "s|RateMe_[0-9]\+\.[0-9]\+\.[0-9]\+-[0-9]\+\.AppImage|RateMe_${VERSION}.AppImage|g" README.md
          sed -i "s|RateMe_[0-9]\+\.[0-9]\+\.[0-9]\+-[0-9]\+_amd64\.deb|RateMe_${VERSION}_amd64.deb|g" README.md
          sed -i "s|RateMe_[0-9]\+\.[0-9]\+\.[0-9]\+-[0-9]\+_x86_64\.rpm|RateMe_${VERSION}_x86_64.rpm|g" README.md
          sed -i "s|RateMe_[0-9]\+\.[0-9]\+\.[0-9]\+-[0-9]\+\.flatpak|RateMe_${VERSION}.flatpak|g" README.md
          
          # Update tarball patterns
          sed -i "s|RateMe_[0-9]\+\.[0-9]\+\.[0-9]\+-[0-9]\+_nixos\.tar\.gz|RateMe_${VERSION}_nixos.tar.gz|g" README.md
          sed -i "s|RateMe_[0-9]\+\.[0-9]\+\.[0-9]\+-[0-9]\+_source\.tar\.gz|RateMe_${VERSION}_source.tar.gz|g" README.md

          # Update website links
          if [ -d "docs" ]; then
            cd docs
            
            # Update all download links
            sed -i "s|/releases/download/v[0-9]\+\.[0-9]\+\.[0-9]\+-[0-9]\+/|/releases/download/v${VERSION}/|g" index.html
            
            # Update individual file patterns
            sed -i "s|RateMe_[0-9]\+\.[0-9]\+\.[0-9]\+-[0-9]\+_nixos\.tar\.gz|RateMe_${VERSION}_nixos.tar.gz|g" index.html
            sed -i "s|RateMe_[0-9]\+\.[0-9]\+\.[0-9]\+-[0-9]\+_source\.tar\.gz|RateMe_${VERSION}_source.tar.gz|g" index.html

            # Update only the universal APK - website doesn't use architecture-specific APKs
            sed -i "s|RateMe_[0-9]\+\.[0-9]\+\.[0-9]\+-[0-9]\+\.apk|RateMe_${VERSION}.apk|g" index.html
            
            # Update any displayed version text
            sed -i "s|Version [0-9]\+\.[0-9]\+\.[0-9]\+-[0-9]\+|Version ${VERSION}|g" index.html
            sed -i "s|\"version\": \"[0-9]\+\.[0-9]\+\.[0-9]\+-[0-9]\+\"|\"version\": \"${VERSION}\"|g" index.html
            
            # Update the fallback version for when GitHub API calls fail
            # This ensures users always see the correct version even if the API request fails
            sed -i "s|document.getElementById('current-version').textContent = '[0-9.]\+-[0-9]\+'|document.getElementById('current-version').textContent = '${VERSION}'|g" index.html
            
            # Verify the update was successful
            echo "Current fallback version updated to: ${VERSION}"
            grep -n "current-version" index.html
            
            # Debug information
            echo "Website changes:"
            git diff index.html
            
            # Commit changes
            git add index.html
            git commit -m "docs: update website to version ${VERSION}" || echo "No changes to website"
            git push || echo "No website changes to push"
          else
            echo "Docs directory not found, skipping website update"
          fi
          
      - name: Update Website
        run: |
          VERSION="${{ needs.create-release.outputs.version }}"
          
          if [ -d "docs" ]; then
            cd docs
            
            # For website, just update the universal APK link and standard app downloads
            # Universal APK is the only Android version linked on the website
            sed -i "s|window.open('https://github.com/ALi3naTEd0/RateMe/releases/download/v[0-9]\+\.[0-9]\+\.[0-9]\+-[0-9]\+/RateMe_[0-9]\+\.[0-9]\+\.[0-9]\+-[0-9]\+\.apk'|window.open('https://github.com/ALi3naTEd0/RateMe/releases/download/v${VERSION}/RateMe_${VERSION}.apk'|g" index.html
            
            # Explicitly update the AppImage link to ensure it's caught
            sed -i "s|href=\"https://github.com/ALi3naTEd0/RateMe/releases/download/v[0-9]\+\.[0-9]\+\.[0-9]\+-[0-9]\+/RateMe_[0-9]\+\.[0-9]\+\.[0-9]\+-[0-9]\+\.AppImage\"|href=\"https://github.com/ALi3naTEd0/RateMe/releases/download/v${VERSION}/RateMe_${VERSION}.AppImage\"|g" index.html
            
            # Update standard download links in the HTML
            sed -i "s|/releases/download/v[0-9]\+\.[0-9]\+\.[0-9]\+-[0-9]\+/|/releases/download/v${VERSION}/|g" index.html
            
            # Individual file patterns to ensure they're all caught
            sed -i "s|RateMe_[0-9]\+\.[0-9]\+\.[0-9]\+-[0-9]\+\.exe|RateMe_${VERSION}.exe|g" index.html
            sed -i "s|RateMe_[0-9]\+\.[0-9]\+\.[0-9]\+-[0-9]\+\.dmg|RateMe_${VERSION}.dmg|g" index.html
            sed -i "s|RateMe_[0-9]\+\.[0-9]\+\.[0-9]\+-[0-9]\+\.AppImage|RateMe_${VERSION}.AppImage|g" index.html  # Additional specific pattern for AppImage
            sed -i "s|RateMe_[0-9]\+\.[0-9]\+\.[0-9]\+-[0-9]\+_amd64\.deb|RateMe_${VERSION}_amd64.deb|g" index.html
            sed -i "s|RateMe_[0-9]\+\.[0-9]\+\.[0-9]\+-[0-9]\+_x86_64\.rpm|RateMe_${VERSION}_x86_64.rpm|g" index.html
            # Add NixOS tar.gz update
            sed -i "s|RateMe_[0-9]\+\.[0-9]\+\.[0-9]\+-[0-9]\+_nixos\.tar\.gz|RateMe_${VERSION}_nixos.tar.gz|g" index.html
            
            # Update only the universal APK - website doesn't use architecture-specific APKs
            sed -i "s|RateMe_[0-9]\+\.[0-9]\+\.[0-9]\+-[0-9]\+\.apk|RateMe_${VERSION}.apk|g" index.html
            
            # Update any displayed version text
            sed -i "s|Version [0-9]\+\.[0-9]\+\.[0-9]\+-[0-9]\+|Version ${VERSION}|g" index.html
            sed -i "s|\"version\": \"[0-9]\+\.[0-9]\+\.[0-9]\+-[0-9]\+\"|\"version\": \"${VERSION}\"|g" index.html
            
            # Update the fallback version for when GitHub API calls fail
            # This ensures users always see the correct version even if the API request fails
            sed -i "s|document.getElementById('current-version').textContent = '[0-9.]\+-[0-9]\+'|document.getElementById('current-version').textContent = '${VERSION}'|g" index.html
            
            # Verify the update was successful
            echo "Current fallback version updated to: ${VERSION}"
            grep -n "current-version" index.html
            
            # Debug information
            echo "Website changes:"
            git diff index.html
            
            # Commit changes
            git add index.html
            git commit -m "docs: update website to version ${VERSION}" || echo "No changes to website"
            git push || echo "No website changes to push"
          else
            echo "Docs directory not found, skipping website update"
          fi
