name: Windows Build

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
          cache: true

      - name: Download Icon
        run: |
          $iconUrl = "https://raw.githubusercontent.com/ALi3naTEd0/RateMe/rateme/assets/rateme.ico"
          $outputPath = "assets/rateme.ico"
          Invoke-WebRequest -Uri $iconUrl -OutFile $outputPath

      - name: Build Windows
        run: |
          flutter config --enable-windows-desktop
          flutter pub get
          flutter build windows --release

      - name: Create Portable ZIP
        shell: pwsh
        run: |
          Compress-Archive -Path "build\windows\x64\runner\Release\*" -DestinationPath "RateMe-Portable.zip"

      - name: Install Inno Setup
        run: |
          choco install innosetup -y

      - name: Create Installer
        shell: pwsh
        run: |
          # Crear directorio Output y ejecutar Inno Setup desde el directorio del proyecto
          New-Item -ItemType Directory -Path "installers\Output" -Force
          & 'C:\Program Files (x86)\Inno Setup 6\ISCC.exe' installers\inno_setup_script.iss

      - name: Upload Portable Version
        uses: actions/upload-artifact@v4
        with:
          name: RateMe-Windows-Portable
          path: RateMe-Portable.zip

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: RateMe-Windows-Setup
          path: installers/Output/RateMe-Setup.exe
