name: Windows Build

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      version:
        description: "Version to build"
        required: true
        type: string
      upload_url:
        required: false
        type: string

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
          cache: true

      - name: Download Icon
        run: |
          mkdir -p assets
          $iconUrl = "https://raw.githubusercontent.com/ALi3naTEd0/RateMe/rateme/assets/rateme.ico"
          $outputPath = "assets/rateme.ico"
          Write-Host "Downloading icon from: $iconUrl"
          Invoke-WebRequest -Uri $iconUrl -OutFile $outputPath
          
          if (Test-Path $outputPath) {
              Write-Host "Icon downloaded successfully to: $outputPath"
          } else {
              Write-Error "Failed to download icon"
              exit 1
          }

      - name: Build Windows
        run: |
          flutter config --enable-windows-desktop
          flutter pub get
          flutter build windows --release

      # Create and upload portable version
      - name: Create Portable Package
        shell: pwsh
        run: |
          # Create directory structure
          $appDir = "RateMe-${{ inputs.version || github.event.inputs.version }}"
          New-Item -ItemType Directory -Path $appDir
          Copy-Item "build\windows\x64\runner\Release\*" -Destination "$appDir\" -Recurse
          
          # Create ZIP preserving directory structure
          Compress-Archive -Path "$appDir" -DestinationPath "RateMe-portable.zip"

      - name: Upload Portable Package
        if: inputs.upload_url == ''
        uses: actions/upload-artifact@v4
        with:
          name: RateMe-Portable
          path: RateMe-portable.zip

      - name: Upload Portable Release Asset
        if: inputs.upload_url != ''
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ inputs.upload_url }}
          asset_path: RateMe-portable.zip
          asset_name: RateMe-portable.zip
          asset_content_type: application/zip

      # Create and upload installer version
      - name: Install Inno Setup
        run: |
          choco install innosetup -y

      - name: Create Installer
        shell: pwsh
        env:
          VERSION: ${{ inputs.version || github.event.inputs.version }}
        run: |
          New-Item -ItemType Directory -Path "installers\Output" -Force
          & 'C:\Program Files (x86)\Inno Setup 6\ISCC.exe' installers\inno_setup_script.iss

      - name: Upload Setup Package
        uses: actions/upload-artifact@v4
        with:
          name: RateMe-Setup
          path: installers/Output/RateMe_${{ inputs.version || github.event.inputs.version }}.exe

      - name: Upload Setup Release Asset
        if: inputs.upload_url != ''
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ inputs.upload_url }}
          asset_path: installers/Output/RateMe_${{ inputs.version || github.event.inputs.version }}.exe
          asset_name: RateMe_${{ inputs.version || github.event.inputs.version }}.exe
          asset_content_type: application/x-msdownload