name: Windows Build

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
          cache: true

      - name: Install Inno Setup
        run: |
          choco install innosetup -y

      - name: Build Windows
        run: |
          flutter config --enable-windows-desktop
          flutter pub get
          flutter build windows --release

      - name: Create Installer
        run: |
          & 'C:\Program Files (x86)\Inno Setup 6\ISCC.exe' installers/inno_setup_script.iss

      - name: Upload Portable
        uses: actions/upload-artifact@v4
        with:
          name: RateMe-Windows-Portable
          path: build/windows/x64/runner/Release/

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: RateMe-Windows-Setup
          path: Output/RateMe-Setup.exe
